// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_45_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        convWidth,
        mul_ln17_1,
        empty,
        mul_ln17,
        mul_ln38,
        mul_ln39_3,
        coeffs,
        icmp_ln1027_1,
        coeff_cache_address0,
        coeff_cache_ce0,
        coeff_cache_we0,
        coeff_cache_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [31:0] m_axi_gmem_WDATA;
output  [3:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [31:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [31:0] convWidth;
input  [95:0] mul_ln17_1;
input  [31:0] empty;
input  [63:0] mul_ln17;
input  [61:0] mul_ln38;
input  [61:0] mul_ln39_3;
input  [63:0] coeffs;
input  [0:0] icmp_ln1027_1;
output  [11:0] coeff_cache_address0;
output   coeff_cache_ce0;
output   coeff_cache_we0;
output  [31:0] coeff_cache_d0;

reg ap_idle;
reg m_axi_gmem_ARVALID;
reg m_axi_gmem_RREADY;
reg coeff_cache_ce0;
reg coeff_cache_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
reg   [0:0] or_ln1027_2_reg_627;
reg   [0:0] or_ln1027_2_reg_627_pp0_iter7_reg;
reg   [0:0] and_ln1027_reg_646;
reg   [0:0] and_ln1027_reg_646_pp0_iter7_reg;
reg    ap_predicate_op109_readreq_state9;
reg    ap_block_state9_io;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
reg   [0:0] icmp_ln1027_4_reg_602;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter14_reg;
reg    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1027_4_fu_256_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_AR;
reg   [0:0] first_iter_0_reg_189;
reg   [0:0] first_iter_01_reg_200;
reg    ap_block_pp0_stage0_11001;
reg   [11:0] cx_V_1_reg_592;
wire   [0:0] icmp_ln1027_fu_251_p2;
reg   [0:0] icmp_ln1027_reg_597;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter2_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter3_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter4_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter5_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter6_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter7_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter8_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter9_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter10_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter11_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter12_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter13_reg;
reg   [0:0] icmp_ln1027_4_reg_602_pp0_iter15_reg;
wire   [0:0] icmp_ln1027_5_fu_276_p2;
reg   [0:0] icmp_ln1027_5_reg_606;
wire   [31:0] select_ln1027_1_fu_281_p3;
reg   [31:0] select_ln1027_1_reg_615;
wire   [0:0] or_ln1027_2_fu_381_p2;
reg   [0:0] or_ln1027_2_reg_627_pp0_iter3_reg;
reg   [0:0] or_ln1027_2_reg_627_pp0_iter4_reg;
reg   [0:0] or_ln1027_2_reg_627_pp0_iter5_reg;
reg   [0:0] or_ln1027_2_reg_627_pp0_iter6_reg;
wire   [11:0] select_ln1027_4_fu_392_p3;
reg   [11:0] select_ln1027_4_reg_631;
wire   [11:0] trunc_ln47_fu_417_p1;
reg   [11:0] trunc_ln47_reg_636;
wire   [9:0] trunc_ln47_1_fu_421_p1;
reg   [9:0] trunc_ln47_1_reg_641;
wire   [0:0] and_ln1027_fu_431_p2;
reg   [0:0] and_ln1027_reg_646_pp0_iter3_reg;
reg   [0:0] and_ln1027_reg_646_pp0_iter4_reg;
reg   [0:0] and_ln1027_reg_646_pp0_iter5_reg;
reg   [0:0] and_ln1027_reg_646_pp0_iter6_reg;
wire   [11:0] add_ln47_1_fu_465_p2;
reg   [11:0] add_ln47_1_reg_651;
reg   [11:0] add_ln47_1_reg_651_pp0_iter4_reg;
reg   [11:0] add_ln47_1_reg_651_pp0_iter5_reg;
reg   [11:0] add_ln47_1_reg_651_pp0_iter6_reg;
reg   [11:0] add_ln47_1_reg_651_pp0_iter7_reg;
wire   [61:0] grp_fu_365_p2;
reg   [61:0] mul_ln1027_reg_656;
reg   [61:0] sext_ln44_mid2_v_reg_661;
reg   [11:0] coeff_cache_addr_reg_666;
reg   [11:0] coeff_cache_addr_reg_666_pp0_iter9_reg;
reg   [11:0] coeff_cache_addr_reg_666_pp0_iter10_reg;
reg   [11:0] coeff_cache_addr_reg_666_pp0_iter11_reg;
reg   [11:0] coeff_cache_addr_reg_666_pp0_iter12_reg;
reg   [11:0] coeff_cache_addr_reg_666_pp0_iter13_reg;
reg   [11:0] coeff_cache_addr_reg_666_pp0_iter14_reg;
reg   [11:0] coeff_cache_addr_reg_666_pp0_iter15_reg;
reg   [31:0] gmem_addr_2_read_reg_681;
reg    ap_condition_exit_pp0_iter2_stage0;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_193_p4;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_first_iter_01_phi_fu_205_p4;
wire   [63:0] zext_ln47_3_fu_500_p1;
wire  signed [63:0] sext_ln1027_fu_497_p1;
reg   [11:0] cx_V_fu_98;
wire   [11:0] add_ln840_fu_437_p2;
reg   [11:0] ap_sig_allocacmp_cx_V_1;
reg   [31:0] cy_V_fu_102;
wire   [31:0] select_ln1027_5_fu_399_p3;
reg   [63:0] indvar_flatten_fu_106;
wire   [63:0] select_ln1027_7_fu_295_p3;
reg   [31:0] iChannel_V_fu_110;
reg   [95:0] indvar_flatten29_fu_114;
wire   [95:0] add_ln1027_3_fu_261_p2;
wire   [31:0] cx_V_cast_fu_247_p1;
wire   [31:0] add_ln840_1_fu_270_p2;
wire   [63:0] add_ln1027_2_fu_289_p2;
wire   [33:0] tmp_3_fu_341_p3;
wire   [34:0] zext_ln47_1_fu_348_p1;
wire   [34:0] zext_ln47_fu_338_p1;
wire   [34:0] sub_ln47_fu_352_p2;
wire   [31:0] grp_fu_365_p0;
wire   [31:0] select_ln1027_fu_326_p3;
wire   [0:0] select_ln1027_3_fu_370_p3;
wire   [0:0] or_ln1027_1_fu_333_p2;
wire   [0:0] or_ln1027_3_fu_387_p2;
wire   [31:0] add_ln840_2_fu_375_p2;
wire  signed [35:0] sext_ln1027_1_fu_358_p1;
wire   [35:0] zext_ln47_2_fu_407_p1;
wire   [35:0] add_ln47_fu_411_p2;
wire   [0:0] or_ln1027_fu_321_p2;
wire   [0:0] xor_ln1027_fu_425_p2;
wire   [11:0] p_shl_fu_453_p3;
wire   [11:0] sub_ln47_1_fu_460_p2;
wire   [61:0] add_ln1027_fu_470_p2;
wire   [63:0] sext_ln44_mid2_v_v_v_v_fu_474_p3;
wire   [63:0] add_ln1027_1_fu_482_p2;
reg    grp_fu_365_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [61:0] grp_fu_365_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_done_reg = 1'b0;
end

Conv2D_HW_mul_32ns_62s_62_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 62 ),
    .dout_WIDTH( 62 ))
mul_32ns_62s_62_5_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_365_p0),
    .din1(mul_ln38),
    .ce(grp_fu_365_ce),
    .dout(grp_fu_365_p2)
);

Conv2D_HW_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter15_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cx_V_fu_98 <= 12'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_4_reg_602 == 1'd0))) begin
            cx_V_fu_98 <= add_ln840_fu_437_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cy_V_fu_102 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_4_reg_602 == 1'd0))) begin
            cy_V_fu_102 <= select_ln1027_5_fu_399_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1027_4_reg_602_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_01_reg_200 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_01_reg_200 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1027_4_reg_602_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_0_reg_189 <= and_ln1027_reg_646;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_0_reg_189 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            iChannel_V_fu_110 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_4_fu_256_p2 == 1'd0))) begin
            iChannel_V_fu_110 <= select_ln1027_1_fu_281_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten29_fu_114 <= 96'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_4_fu_256_p2 == 1'd0))) begin
            indvar_flatten29_fu_114 <= add_ln1027_3_fu_261_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_106 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_4_fu_256_p2 == 1'd0))) begin
            indvar_flatten_fu_106 <= select_ln1027_7_fu_295_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_4_reg_602_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln47_1_reg_651 <= add_ln47_1_fu_465_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln47_1_reg_651_pp0_iter4_reg <= add_ln47_1_reg_651;
        add_ln47_1_reg_651_pp0_iter5_reg <= add_ln47_1_reg_651_pp0_iter4_reg;
        add_ln47_1_reg_651_pp0_iter6_reg <= add_ln47_1_reg_651_pp0_iter5_reg;
        add_ln47_1_reg_651_pp0_iter7_reg <= add_ln47_1_reg_651_pp0_iter6_reg;
        and_ln1027_reg_646_pp0_iter3_reg <= and_ln1027_reg_646;
        and_ln1027_reg_646_pp0_iter4_reg <= and_ln1027_reg_646_pp0_iter3_reg;
        and_ln1027_reg_646_pp0_iter5_reg <= and_ln1027_reg_646_pp0_iter4_reg;
        and_ln1027_reg_646_pp0_iter6_reg <= and_ln1027_reg_646_pp0_iter5_reg;
        and_ln1027_reg_646_pp0_iter7_reg <= and_ln1027_reg_646_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        coeff_cache_addr_reg_666_pp0_iter10_reg <= coeff_cache_addr_reg_666_pp0_iter9_reg;
        coeff_cache_addr_reg_666_pp0_iter11_reg <= coeff_cache_addr_reg_666_pp0_iter10_reg;
        coeff_cache_addr_reg_666_pp0_iter12_reg <= coeff_cache_addr_reg_666_pp0_iter11_reg;
        coeff_cache_addr_reg_666_pp0_iter13_reg <= coeff_cache_addr_reg_666_pp0_iter12_reg;
        coeff_cache_addr_reg_666_pp0_iter14_reg <= coeff_cache_addr_reg_666_pp0_iter13_reg;
        coeff_cache_addr_reg_666_pp0_iter15_reg <= coeff_cache_addr_reg_666_pp0_iter14_reg;
        coeff_cache_addr_reg_666_pp0_iter9_reg <= coeff_cache_addr_reg_666;
        icmp_ln1027_4_reg_602_pp0_iter10_reg <= icmp_ln1027_4_reg_602_pp0_iter9_reg;
        icmp_ln1027_4_reg_602_pp0_iter11_reg <= icmp_ln1027_4_reg_602_pp0_iter10_reg;
        icmp_ln1027_4_reg_602_pp0_iter12_reg <= icmp_ln1027_4_reg_602_pp0_iter11_reg;
        icmp_ln1027_4_reg_602_pp0_iter13_reg <= icmp_ln1027_4_reg_602_pp0_iter12_reg;
        icmp_ln1027_4_reg_602_pp0_iter14_reg <= icmp_ln1027_4_reg_602_pp0_iter13_reg;
        icmp_ln1027_4_reg_602_pp0_iter15_reg <= icmp_ln1027_4_reg_602_pp0_iter14_reg;
        icmp_ln1027_4_reg_602_pp0_iter2_reg <= icmp_ln1027_4_reg_602;
        icmp_ln1027_4_reg_602_pp0_iter3_reg <= icmp_ln1027_4_reg_602_pp0_iter2_reg;
        icmp_ln1027_4_reg_602_pp0_iter4_reg <= icmp_ln1027_4_reg_602_pp0_iter3_reg;
        icmp_ln1027_4_reg_602_pp0_iter5_reg <= icmp_ln1027_4_reg_602_pp0_iter4_reg;
        icmp_ln1027_4_reg_602_pp0_iter6_reg <= icmp_ln1027_4_reg_602_pp0_iter5_reg;
        icmp_ln1027_4_reg_602_pp0_iter7_reg <= icmp_ln1027_4_reg_602_pp0_iter6_reg;
        icmp_ln1027_4_reg_602_pp0_iter8_reg <= icmp_ln1027_4_reg_602_pp0_iter7_reg;
        icmp_ln1027_4_reg_602_pp0_iter9_reg <= icmp_ln1027_4_reg_602_pp0_iter8_reg;
        or_ln1027_2_reg_627_pp0_iter3_reg <= or_ln1027_2_reg_627;
        or_ln1027_2_reg_627_pp0_iter4_reg <= or_ln1027_2_reg_627_pp0_iter3_reg;
        or_ln1027_2_reg_627_pp0_iter5_reg <= or_ln1027_2_reg_627_pp0_iter4_reg;
        or_ln1027_2_reg_627_pp0_iter6_reg <= or_ln1027_2_reg_627_pp0_iter5_reg;
        or_ln1027_2_reg_627_pp0_iter7_reg <= or_ln1027_2_reg_627_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_4_reg_602 == 1'd0))) begin
        and_ln1027_reg_646 <= and_ln1027_fu_431_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        cx_V_1_reg_592 <= ap_sig_allocacmp_cx_V_1;
        icmp_ln1027_4_reg_602 <= icmp_ln1027_4_fu_256_p2;
        icmp_ln1027_reg_597 <= icmp_ln1027_fu_251_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_4_reg_602_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        coeff_cache_addr_reg_666 <= zext_ln47_3_fu_500_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_4_reg_602_pp0_iter14_reg == 1'd0))) begin
        gmem_addr_2_read_reg_681 <= m_axi_gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_4_fu_256_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln1027_5_reg_606 <= icmp_ln1027_5_fu_276_p2;
        select_ln1027_1_reg_615 <= select_ln1027_1_fu_281_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_4_reg_602_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln1027_reg_656 <= grp_fu_365_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_4_reg_602 == 1'd0))) begin
        or_ln1027_2_reg_627 <= or_ln1027_2_fu_381_p2;
        select_ln1027_4_reg_631 <= select_ln1027_4_fu_392_p3;
        trunc_ln47_1_reg_641 <= trunc_ln47_1_fu_421_p1;
        trunc_ln47_reg_636 <= trunc_ln47_fu_417_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_4_reg_602_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sext_ln44_mid2_v_reg_661 <= {{add_ln1027_1_fu_482_p2[63:2]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_4_fu_256_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln1027_4_reg_602 == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter15_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1027_4_reg_602_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_01_phi_fu_205_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_01_phi_fu_205_p4 = first_iter_01_reg_200;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1027_4_reg_602_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_0_phi_fu_193_p4 = and_ln1027_reg_646;
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_193_p4 = first_iter_0_reg_189;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln1027_4_reg_602 == 1'd0))) begin
        ap_sig_allocacmp_cx_V_1 = add_ln840_fu_437_p2;
    end else begin
        ap_sig_allocacmp_cx_V_1 = cx_V_fu_98;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        coeff_cache_ce0 = 1'b1;
    end else begin
        coeff_cache_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (icmp_ln1027_4_reg_602_pp0_iter15_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        coeff_cache_we0 = 1'b1;
    end else begin
        coeff_cache_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op109_readreq_state9 == 1'b1))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln1027_4_reg_602_pp0_iter14_reg == 1'd0))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_365_ce = 1'b1;
    end else begin
        grp_fu_365_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op109_readreq_state9 == 1'b1))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_4_reg_602_pp0_iter14_reg == 1'd0))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1027_1_fu_482_p2 = (sext_ln44_mid2_v_v_v_v_fu_474_p3 + coeffs);

assign add_ln1027_2_fu_289_p2 = (indvar_flatten_fu_106 + 64'd1);

assign add_ln1027_3_fu_261_p2 = (indvar_flatten29_fu_114 + 96'd1);

assign add_ln1027_fu_470_p2 = (mul_ln1027_reg_656 + mul_ln39_3);

assign add_ln47_1_fu_465_p2 = (sub_ln47_1_fu_460_p2 + select_ln1027_4_reg_631);

assign add_ln47_fu_411_p2 = ($signed(sext_ln1027_1_fu_358_p1) + $signed(zext_ln47_2_fu_407_p1));

assign add_ln840_1_fu_270_p2 = (iChannel_V_fu_110 + 32'd1);

assign add_ln840_2_fu_375_p2 = (select_ln1027_fu_326_p3 + 32'd1);

assign add_ln840_fu_437_p2 = (select_ln1027_4_fu_392_p3 + 12'd1);

assign and_ln1027_fu_431_p2 = (xor_ln1027_fu_425_p2 & or_ln1027_fu_321_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln1027_4_reg_602_pp0_iter14_reg == 1'd0) & (m_axi_gmem_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln1027_4_reg_602_pp0_iter14_reg == 1'd0) & (m_axi_gmem_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state16_pp0_stage0_iter15 = ((icmp_ln1027_4_reg_602_pp0_iter14_reg == 1'd0) & (m_axi_gmem_RVALID == 1'b0));
end

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((ap_predicate_op109_readreq_state9 == 1'b1) & (m_axi_gmem_ARREADY == 1'b0));
end

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op109_readreq_state9 = ((1'd1 == and_ln1027_reg_646_pp0_iter7_reg) & (or_ln1027_2_reg_627_pp0_iter7_reg == 1'd1));
end

assign coeff_cache_address0 = coeff_cache_addr_reg_666_pp0_iter15_reg;

assign coeff_cache_d0 = gmem_addr_2_read_reg_681;

assign cx_V_cast_fu_247_p1 = ap_sig_allocacmp_cx_V_1;

assign grp_fu_365_p0 = grp_fu_365_p00;

assign grp_fu_365_p00 = select_ln1027_1_reg_615;

assign icmp_ln1027_4_fu_256_p2 = ((indvar_flatten29_fu_114 == mul_ln17_1) ? 1'b1 : 1'b0);

assign icmp_ln1027_5_fu_276_p2 = ((indvar_flatten_fu_106 == mul_ln17) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_251_p2 = ((cx_V_cast_fu_247_p1 == convWidth) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = sext_ln1027_fu_497_p1;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = empty;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 32'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 4'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign or_ln1027_1_fu_333_p2 = (icmp_ln1027_5_reg_606 | ap_phi_mux_first_iter_01_phi_fu_205_p4);

assign or_ln1027_2_fu_381_p2 = (select_ln1027_3_fu_370_p3 | or_ln1027_1_fu_333_p2);

assign or_ln1027_3_fu_387_p2 = (select_ln1027_3_fu_370_p3 | icmp_ln1027_5_reg_606);

assign or_ln1027_fu_321_p2 = (icmp_ln1027_5_reg_606 | ap_phi_mux_first_iter_0_phi_fu_193_p4);

assign p_shl_fu_453_p3 = {{trunc_ln47_1_reg_641}, {2'd0}};

assign select_ln1027_1_fu_281_p3 = ((icmp_ln1027_5_fu_276_p2[0:0] == 1'b1) ? add_ln840_1_fu_270_p2 : iChannel_V_fu_110);

assign select_ln1027_3_fu_370_p3 = ((icmp_ln1027_5_reg_606[0:0] == 1'b1) ? icmp_ln1027_1 : icmp_ln1027_reg_597);

assign select_ln1027_4_fu_392_p3 = ((or_ln1027_3_fu_387_p2[0:0] == 1'b1) ? 12'd0 : cx_V_1_reg_592);

assign select_ln1027_5_fu_399_p3 = ((select_ln1027_3_fu_370_p3[0:0] == 1'b1) ? add_ln840_2_fu_375_p2 : select_ln1027_fu_326_p3);

assign select_ln1027_7_fu_295_p3 = ((icmp_ln1027_5_fu_276_p2[0:0] == 1'b1) ? 64'd1 : add_ln1027_2_fu_289_p2);

assign select_ln1027_fu_326_p3 = ((icmp_ln1027_5_reg_606[0:0] == 1'b1) ? 32'd0 : cy_V_fu_102);

assign sext_ln1027_1_fu_358_p1 = $signed(sub_ln47_fu_352_p2);

assign sext_ln1027_fu_497_p1 = $signed(sext_ln44_mid2_v_reg_661);

assign sext_ln44_mid2_v_v_v_v_fu_474_p3 = {{add_ln1027_fu_470_p2}, {2'd0}};

assign sub_ln47_1_fu_460_p2 = (p_shl_fu_453_p3 - trunc_ln47_reg_636);

assign sub_ln47_fu_352_p2 = (zext_ln47_1_fu_348_p1 - zext_ln47_fu_338_p1);

assign tmp_3_fu_341_p3 = {{select_ln1027_1_reg_615}, {2'd0}};

assign trunc_ln47_1_fu_421_p1 = add_ln47_fu_411_p2[9:0];

assign trunc_ln47_fu_417_p1 = add_ln47_fu_411_p2[11:0];

assign xor_ln1027_fu_425_p2 = (select_ln1027_3_fu_370_p3 ^ 1'd1);

assign zext_ln47_1_fu_348_p1 = tmp_3_fu_341_p3;

assign zext_ln47_2_fu_407_p1 = select_ln1027_5_fu_399_p3;

assign zext_ln47_3_fu_500_p1 = add_ln47_1_reg_651_pp0_iter7_reg;

assign zext_ln47_fu_338_p1 = select_ln1027_1_reg_615;

endmodule //Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_45_4
