// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Conv2D_HW_Conv2D_HW,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=8153,HLS_SYN_LUT=6769,HLS_VERSION=2022_2}" *)

module Conv2D_HW (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_state23 = 28'd4194304;
parameter    ap_ST_fsm_state24 = 28'd8388608;
parameter    ap_ST_fsm_state25 = 28'd16777216;
parameter    ap_ST_fsm_state26 = 28'd33554432;
parameter    ap_ST_fsm_state27 = 28'd67108864;
parameter    ap_ST_fsm_state28 = 28'd134217728;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_r;
wire   [63:0] output_r;
wire   [63:0] coeffs;
wire   [63:0] biases;
wire   [31:0] numChannels;
wire   [31:0] numFilters;
wire   [31:0] inputWidth;
wire   [31:0] inputHeight;
wire   [31:0] convWidth;
wire   [31:0] convHeight;
wire   [0:0] apply_relu;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state10;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state19;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state23;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state28;
reg    gmem_blk_n_AW;
reg   [0:0] apply_relu_read_reg_634;
reg   [31:0] convHeight_read_reg_639;
reg   [31:0] convWidth_read_reg_645;
reg   [31:0] inputHeight_read_reg_654;
reg   [31:0] inputWidth_read_reg_660;
reg   [31:0] numFilters_read_reg_668;
reg   [31:0] numChannels_read_reg_673;
reg   [63:0] biases_read_reg_679;
reg   [63:0] coeffs_read_reg_684;
reg   [63:0] output_r_read_reg_689;
reg   [63:0] input_r_read_reg_694;
wire    ap_CS_fsm_state2;
wire   [63:0] grp_fu_300_p2;
reg   [63:0] mul_ln16_reg_715;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire  signed [32:0] sub_i_i468_fu_321_p2;
reg  signed [32:0] sub_i_i468_reg_731;
wire    ap_CS_fsm_state6;
wire   [61:0] convHeight_cast_fu_327_p1;
wire    ap_CS_fsm_state7;
wire   [61:0] convWidth_cast_fu_330_p1;
wire   [32:0] sub_i_i438_fu_354_p2;
reg   [32:0] sub_i_i438_reg_758;
wire    ap_CS_fsm_state8;
wire   [61:0] numChannels_cast_fu_360_p1;
reg   [61:0] numChannels_cast_reg_763;
wire  signed [63:0] add_ln37_cast_fu_369_p1;
reg  signed [63:0] add_ln37_cast_reg_768;
wire  signed [63:0] sext_ln39_1_fu_389_p1;
reg  signed [63:0] sext_ln39_1_reg_773;
wire   [31:0] empty_fu_398_p3;
reg   [31:0] empty_reg_778;
wire   [61:0] grp_fu_333_p2;
reg   [61:0] tmp1_reg_783;
wire   [95:0] grp_fu_312_p2;
reg   [95:0] mul_ln16_1_reg_788;
wire   [64:0] grp_fu_345_p2;
reg   [64:0] mul_ln16_2_reg_793;
wire   [0:0] icmp_ln1027_fu_406_p2;
reg   [0:0] icmp_ln1027_reg_798;
wire   [64:0] add_ln1027_1_fu_431_p2;
reg   [64:0] add_ln1027_1_reg_806;
wire    ap_CS_fsm_state9;
wire   [31:0] select_ln1027_fu_440_p3;
reg   [31:0] select_ln1027_reg_811;
wire   [0:0] icmp_ln1027_3_fu_426_p2;
wire   [31:0] select_ln1027_1_fu_454_p3;
reg   [31:0] select_ln1027_1_reg_819;
reg   [63:0] gmem_addr_reg_826;
wire   [63:0] grp_fu_502_p2;
reg   [63:0] mul_ln1027_reg_837;
wire    ap_CS_fsm_state11;
wire  signed [63:0] tmp_fu_510_p2;
reg  signed [63:0] tmp_reg_842;
wire    ap_CS_fsm_state12;
wire   [63:0] grp_fu_515_p2;
reg   [63:0] empty_42_reg_847;
wire    ap_CS_fsm_state17;
wire   [61:0] zext_ln1027_2_fu_519_p1;
wire    ap_CS_fsm_state18;
reg   [63:0] gmem_addr_1_reg_857;
wire   [61:0] grp_fu_522_p2;
reg   [61:0] mul_ln1027_1_reg_863;
reg   [31:0] gmem_addr_read_reg_868;
wire   [31:0] x_V_1_fu_560_p2;
reg   [31:0] x_V_1_reg_876;
wire    ap_CS_fsm_state20;
wire   [31:0] acc_2_fu_605_p3;
reg   [31:0] acc_2_reg_881;
wire    ap_CS_fsm_state22;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_start;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_done;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_idle;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_ready;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WVALID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WDATA;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WSTRB;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WLAST;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WID;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_RREADY;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_BREADY;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_acc_2_out;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_acc_2_out_ap_vld;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_333_p_din0;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_333_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_333_p_ce;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_522_p_din0;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_522_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_522_p_ce;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg   [31:0] x_V_reg_245;
reg    grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_start_reg;
wire   [0:0] icmp_ln1027_2_fu_555_p2;
wire    ap_CS_fsm_state21;
wire  signed [63:0] sext_ln1027_fu_489_p1;
wire  signed [63:0] sext_ln39_fu_541_p1;
reg   [31:0] y_V_fu_136;
wire   [31:0] y_V_3_fu_566_p2;
reg   [31:0] iFilter_V_fu_140;
reg   [64:0] indvar_flatten91_fu_144;
wire   [31:0] grp_fu_300_p0;
wire   [31:0] grp_fu_300_p1;
wire   [31:0] grp_fu_312_p0;
wire   [63:0] grp_fu_312_p1;
wire   [32:0] inputHeight_cast_fu_318_p1;
reg   [31:0] grp_fu_333_p0;
reg   [31:0] grp_fu_333_p1;
wire   [31:0] grp_fu_345_p0;
wire   [32:0] grp_fu_345_p1;
wire   [32:0] inputWidth_cast_fu_351_p1;
wire   [33:0] tmp_1_fu_372_p3;
wire   [34:0] p_cast_fu_379_p1;
wire   [34:0] tmp2_fu_383_p2;
wire   [0:0] cmp_i4151137_fu_363_p2;
wire   [31:0] add_ln39_fu_393_p2;
wire   [32:0] zext_ln1027_fu_417_p1;
wire   [0:0] icmp_ln1027_1_fu_421_p2;
wire   [31:0] add_ln840_fu_448_p2;
wire   [33:0] p_cast7_cast_mid2_v_v_v_v_v_fu_462_p3;
wire   [63:0] zext_ln1027_3_fu_470_p1;
wire   [63:0] add_ln1027_fu_474_p2;
wire   [61:0] p_cast7_cast_mid2_v_fu_479_p4;
wire   [31:0] grp_fu_502_p0;
wire  signed [32:0] grp_fu_502_p1;
wire   [63:0] y_V_cast15_fu_507_p1;
wire  signed [34:0] grp_fu_515_p1;
wire    ap_CS_fsm_state13;
reg   [31:0] grp_fu_522_p0;
reg   [31:0] grp_fu_522_p1;
wire   [63:0] empty_43_fu_527_p2;
wire   [61:0] trunc_ln_fu_531_p4;
wire   [32:0] zext_ln1027_4_fu_551_p1;
wire   [31:0] acc_fu_587_p2;
wire   [0:0] tmp_2_fu_592_p3;
wire   [0:0] and_ln56_fu_600_p2;
reg    grp_fu_333_ce;
reg    grp_fu_502_ce;
reg    grp_fu_522_ce;
reg   [27:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
wire   [63:0] grp_fu_300_p00;
wire   [63:0] grp_fu_300_p10;
wire   [95:0] grp_fu_312_p00;
wire   [95:0] grp_fu_312_p10;
wire   [64:0] grp_fu_345_p00;
wire   [64:0] grp_fu_345_p10;
wire   [63:0] grp_fu_502_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_start_reg = 1'b0;
end

Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6 grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_start),
    .ap_done(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_done),
    .ap_idle(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_idle),
    .ap_ready(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_ready),
    .m_axi_gmem_AWVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .inputHeight_cast11(inputHeight_read_reg_654),
    .zext_ln39(select_ln1027_reg_811),
    .convWidth_cast(convWidth_read_reg_645),
    .mul_ln16_1(mul_ln16_1_reg_788),
    .mul_ln16(mul_ln16_reg_715),
    .mul_ln1027_1(mul_ln1027_1_reg_863),
    .tmp1(tmp1_reg_783),
    .coeffs(coeffs_read_reg_684),
    .tmp3_cast_mid144(select_ln1027_reg_811),
    .convWidth(convWidth_read_reg_645),
    .icmp_ln1027(icmp_ln1027_reg_798),
    .inputWidth_cast12(inputWidth_read_reg_660),
    .x_V_cast16(x_V_reg_245),
    .input_r(input_r_read_reg_694),
    .acc_2_out(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_acc_2_out),
    .acc_2_out_ap_vld(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_acc_2_out_ap_vld),
    .grp_fu_333_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_333_p_din0),
    .grp_fu_333_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_333_p_din1),
    .grp_fu_333_p_dout0(grp_fu_333_p2),
    .grp_fu_333_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_333_p_ce),
    .grp_fu_522_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_522_p_din0),
    .grp_fu_522_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_522_p_din1),
    .grp_fu_522_p_dout0(grp_fu_522_p2),
    .grp_fu_522_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_522_p_ce)
);

Conv2D_HW_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .output_r(output_r),
    .coeffs(coeffs),
    .biases(biases),
    .numChannels(numChannels),
    .numFilters(numFilters),
    .inputWidth(inputWidth),
    .inputHeight(inputHeight),
    .convWidth(convWidth),
    .convHeight(convHeight),
    .apply_relu(apply_relu),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

Conv2D_HW_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_1_reg_857),
    .I_AWLEN(empty_reg_778),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(acc_2_reg_881),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

Conv2D_HW_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U28(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_300_p0),
    .din1(grp_fu_300_p1),
    .ce(1'b1),
    .dout(grp_fu_300_p2)
);

Conv2D_HW_mul_32ns_64ns_96_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 96 ))
mul_32ns_64ns_96_5_1_U29(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_312_p0),
    .din1(grp_fu_312_p1),
    .ce(1'b1),
    .dout(grp_fu_312_p2)
);

Conv2D_HW_mul_32ns_32ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 62 ))
mul_32ns_32ns_62_2_1_U30(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_333_p0),
    .din1(grp_fu_333_p1),
    .ce(grp_fu_333_ce),
    .dout(grp_fu_333_p2)
);

Conv2D_HW_mul_32ns_33ns_65_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 33 ),
    .dout_WIDTH( 65 ))
mul_32ns_33ns_65_2_1_U31(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_345_p0),
    .din1(grp_fu_345_p1),
    .ce(1'b1),
    .dout(grp_fu_345_p2)
);

Conv2D_HW_mul_32ns_33s_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 33 ),
    .dout_WIDTH( 64 ))
mul_32ns_33s_64_2_1_U32(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_502_p0),
    .din1(grp_fu_502_p1),
    .ce(grp_fu_502_ce),
    .dout(grp_fu_502_p2)
);

Conv2D_HW_mul_64s_35s_64_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 35 ),
    .dout_WIDTH( 64 ))
mul_64s_35s_64_5_1_U33(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp_reg_842),
    .din1(grp_fu_515_p1),
    .ce(1'b1),
    .dout(grp_fu_515_p2)
);

Conv2D_HW_mul_32ns_32ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 62 ))
mul_32ns_32ns_62_2_1_U34(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_522_p0),
    .din1(grp_fu_522_p1),
    .ce(grp_fu_522_ce),
    .dout(grp_fu_522_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1027_2_fu_555_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_start_reg <= 1'b1;
        end else if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_ready == 1'b1)) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        iFilter_V_fu_140 <= 32'd0;
    end else if (((icmp_ln1027_2_fu_555_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        iFilter_V_fu_140 <= select_ln1027_1_reg_819;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten91_fu_144 <= 65'd0;
    end else if (((icmp_ln1027_2_fu_555_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        indvar_flatten91_fu_144 <= add_ln1027_1_reg_806;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        x_V_reg_245 <= x_V_1_reg_876;
    end else if ((~((gmem_RVALID == 1'b0) | (gmem_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state19))) begin
        x_V_reg_245 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_V_fu_136 <= 32'd0;
    end else if (((icmp_ln1027_2_fu_555_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        y_V_fu_136 <= y_V_3_fu_566_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        acc_2_reg_881 <= acc_2_fu_605_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln1027_1_reg_806 <= add_ln1027_1_fu_431_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln37_cast_reg_768 <= add_ln37_cast_fu_369_p1;
        empty_reg_778 <= empty_fu_398_p3;
        icmp_ln1027_reg_798 <= icmp_ln1027_fu_406_p2;
        mul_ln16_1_reg_788 <= grp_fu_312_p2;
        mul_ln16_2_reg_793 <= grp_fu_345_p2;
        numChannels_cast_reg_763[31 : 0] <= numChannels_cast_fu_360_p1[31 : 0];
        sext_ln39_1_reg_773[63 : 2] <= sext_ln39_1_fu_389_p1[63 : 2];
        sub_i_i438_reg_758 <= sub_i_i438_fu_354_p2;
        tmp1_reg_783 <= grp_fu_333_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        apply_relu_read_reg_634 <= apply_relu;
        biases_read_reg_679 <= biases;
        coeffs_read_reg_684 <= coeffs;
        convHeight_read_reg_639 <= convHeight;
        convWidth_read_reg_645 <= convWidth;
        inputHeight_read_reg_654 <= inputHeight;
        inputWidth_read_reg_660 <= inputWidth;
        input_r_read_reg_694 <= input_r;
        numChannels_read_reg_673 <= numChannels;
        numFilters_read_reg_668 <= numFilters;
        output_r_read_reg_689 <= output_r;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        empty_42_reg_847 <= grp_fu_515_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        gmem_addr_1_reg_857 <= sext_ln39_fu_541_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        gmem_addr_read_reg_868 <= gmem_RDATA;
        mul_ln1027_1_reg_863 <= grp_fu_522_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_3_fu_426_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        gmem_addr_reg_826 <= sext_ln1027_fu_489_p1;
        select_ln1027_1_reg_819 <= select_ln1027_1_fu_454_p3;
        select_ln1027_reg_811 <= select_ln1027_fu_440_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        mul_ln1027_reg_837 <= grp_fu_502_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln16_reg_715 <= grp_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sub_i_i468_reg_731 <= sub_i_i468_fu_321_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_reg_842 <= tmp_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        x_V_1_reg_876 <= x_V_1_fu_560_p2;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if (((gmem_RVALID == 1'b0) | (gmem_AWREADY == 1'b0))) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((gmem_WREADY == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

always @ (*) begin
    if ((gmem_BVALID == 1'b0)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln1027_3_fu_426_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1027_3_fu_426_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARADDR = gmem_addr_reg_826;
    end else if (((1'b1 == ap_CS_fsm_state21) | ((icmp_ln1027_2_fu_555_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20)))) begin
        gmem_ARADDR = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARLEN = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state21) | ((icmp_ln1027_2_fu_555_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20)))) begin
        gmem_ARLEN = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state21) | ((icmp_ln1027_2_fu_555_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20)))) begin
        gmem_ARVALID = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((gmem_RVALID == 1'b0) | (gmem_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state19))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((gmem_RVALID == 1'b0) | (gmem_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state19))) begin
        gmem_RREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state21) | ((icmp_ln1027_2_fu_555_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20)))) begin
        gmem_RREADY = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_333_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_333_p_ce;
    end else begin
        grp_fu_333_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_333_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_333_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_333_p0 = convWidth_cast_fu_330_p1;
    end else begin
        grp_fu_333_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_333_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_333_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_333_p1 = convHeight_cast_fu_327_p1;
    end else begin
        grp_fu_333_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        grp_fu_502_ce = 1'b1;
    end else begin
        grp_fu_502_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_522_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_522_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state18) | (~((gmem_RVALID == 1'b0) | (gmem_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state19)))) begin
        grp_fu_522_ce = 1'b1;
    end else begin
        grp_fu_522_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_522_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_522_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_522_p0 = zext_ln1027_2_fu_519_p1;
    end else begin
        grp_fu_522_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_522_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_grp_fu_522_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_522_p1 = numChannels_cast_reg_763;
    end else begin
        grp_fu_522_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln1027_3_fu_426_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if ((~((gmem_RVALID == 1'b0) | (gmem_AWREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((icmp_ln1027_2_fu_555_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_2_fu_605_p3 = ((and_ln56_fu_600_p2[0:0] == 1'b1) ? 32'd0 : acc_fu_587_p2);

assign acc_fu_587_p2 = (gmem_addr_read_reg_868 + grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_acc_2_out);

assign add_ln1027_1_fu_431_p2 = (indvar_flatten91_fu_144 + 65'd1);

assign add_ln1027_fu_474_p2 = (zext_ln1027_3_fu_470_p1 + biases_read_reg_679);

assign add_ln37_cast_fu_369_p1 = sub_i_i468_reg_731;

assign add_ln39_fu_393_p2 = ($signed(inputWidth_read_reg_660) + $signed(32'd4294967294));

assign add_ln840_fu_448_p2 = (iFilter_V_fu_140 + 32'd1);

assign and_ln56_fu_600_p2 = (tmp_2_fu_592_p3 & apply_relu_read_reg_634);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp_i4151137_fu_363_p2 = (($signed(sub_i_i438_fu_354_p2) > $signed(33'd0)) ? 1'b1 : 1'b0);

assign convHeight_cast_fu_327_p1 = convHeight_read_reg_639;

assign convWidth_cast_fu_330_p1 = convWidth_read_reg_645;

assign empty_43_fu_527_p2 = (empty_42_reg_847 + output_r_read_reg_689);

assign empty_fu_398_p3 = ((cmp_i4151137_fu_363_p2[0:0] == 1'b1) ? add_ln39_fu_393_p2 : 32'd0);

assign grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_start = grp_Conv2D_HW_Pipeline_VITIS_LOOP_42_4_VITIS_LOOP_43_5_VITIS_LOOP_44_6_fu_257_ap_start_reg;

assign grp_fu_300_p0 = grp_fu_300_p00;

assign grp_fu_300_p00 = convHeight_read_reg_639;

assign grp_fu_300_p1 = grp_fu_300_p10;

assign grp_fu_300_p10 = convWidth_read_reg_645;

assign grp_fu_312_p0 = grp_fu_312_p00;

assign grp_fu_312_p00 = numChannels_read_reg_673;

assign grp_fu_312_p1 = grp_fu_312_p10;

assign grp_fu_312_p10 = mul_ln16_reg_715;

assign grp_fu_345_p0 = grp_fu_345_p00;

assign grp_fu_345_p00 = numFilters_read_reg_668;

assign grp_fu_345_p1 = grp_fu_345_p10;

assign grp_fu_345_p10 = $unsigned(sub_i_i468_reg_731);

assign grp_fu_502_p0 = grp_fu_502_p00;

assign grp_fu_502_p00 = select_ln1027_1_reg_819;

assign grp_fu_502_p1 = add_ln37_cast_reg_768;

assign grp_fu_515_p1 = sext_ln39_1_reg_773;

assign icmp_ln1027_1_fu_421_p2 = (($signed(sub_i_i468_reg_731) > $signed(zext_ln1027_fu_417_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1027_2_fu_555_p2 = (($signed(sub_i_i438_reg_758) > $signed(zext_ln1027_4_fu_551_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1027_3_fu_426_p2 = ((indvar_flatten91_fu_144 == mul_ln16_2_reg_793) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_406_p2 = ((convWidth_read_reg_645 == 32'd0) ? 1'b1 : 1'b0);

assign inputHeight_cast_fu_318_p1 = inputHeight_read_reg_654;

assign inputWidth_cast_fu_351_p1 = inputWidth_read_reg_660;

assign numChannels_cast_fu_360_p1 = numChannels_read_reg_673;

assign p_cast7_cast_mid2_v_fu_479_p4 = {{add_ln1027_fu_474_p2[63:2]}};

assign p_cast7_cast_mid2_v_v_v_v_v_fu_462_p3 = {{select_ln1027_1_fu_454_p3}, {2'd0}};

assign p_cast_fu_379_p1 = tmp_1_fu_372_p3;

assign select_ln1027_1_fu_454_p3 = ((icmp_ln1027_1_fu_421_p2[0:0] == 1'b1) ? iFilter_V_fu_140 : add_ln840_fu_448_p2);

assign select_ln1027_fu_440_p3 = ((icmp_ln1027_1_fu_421_p2[0:0] == 1'b1) ? y_V_fu_136 : 32'd0);

assign sext_ln1027_fu_489_p1 = $signed(p_cast7_cast_mid2_v_fu_479_p4);

assign sext_ln39_1_fu_389_p1 = $signed(tmp2_fu_383_p2);

assign sext_ln39_fu_541_p1 = $signed(trunc_ln_fu_531_p4);

assign sub_i_i438_fu_354_p2 = ($signed(inputWidth_cast_fu_351_p1) + $signed(33'd8589934590));

assign sub_i_i468_fu_321_p2 = ($signed(inputHeight_cast_fu_318_p1) + $signed(33'd8589934590));

assign tmp2_fu_383_p2 = ($signed(p_cast_fu_379_p1) + $signed(35'd34359738360));

assign tmp_1_fu_372_p3 = {{inputWidth_read_reg_660}, {2'd0}};

assign tmp_2_fu_592_p3 = acc_fu_587_p2[32'd31];

assign tmp_fu_510_p2 = (mul_ln1027_reg_837 + y_V_cast15_fu_507_p1);

assign trunc_ln_fu_531_p4 = {{empty_43_fu_527_p2[63:2]}};

assign x_V_1_fu_560_p2 = (x_V_reg_245 + 32'd1);

assign y_V_3_fu_566_p2 = (select_ln1027_reg_811 + 32'd1);

assign y_V_cast15_fu_507_p1 = select_ln1027_reg_811;

assign zext_ln1027_2_fu_519_p1 = select_ln1027_1_reg_819;

assign zext_ln1027_3_fu_470_p1 = p_cast7_cast_mid2_v_v_v_v_v_fu_462_p3;

assign zext_ln1027_4_fu_551_p1 = x_V_reg_245;

assign zext_ln1027_fu_417_p1 = y_V_fu_136;

always @ (posedge ap_clk) begin
    numChannels_cast_reg_763[61:32] <= 30'b000000000000000000000000000000;
    sext_ln39_1_reg_773[1:0] <= 2'b00;
end

endmodule //Conv2D_HW
