-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_66_8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    y_V : IN STD_LOGIC_VECTOR (31 downto 0);
    inputHeight_cast7 : IN STD_LOGIC_VECTOR (31 downto 0);
    inputWidth : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln17_3 : IN STD_LOGIC_VECTOR (95 downto 0);
    mul_ln17_2 : IN STD_LOGIC_VECTOR (63 downto 0);
    icmp_ln1027_3 : IN STD_LOGIC_VECTOR (0 downto 0);
    inputWidth_cast8 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_r : IN STD_LOGIC_VECTOR (63 downto 0);
    row_buffer_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    row_buffer_ce0 : OUT STD_LOGIC;
    row_buffer_we0 : OUT STD_LOGIC;
    row_buffer_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_400_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_400_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_400_p_dout0 : IN STD_LOGIC_VECTOR (61 downto 0);
    grp_fu_400_p_ce : OUT STD_LOGIC;
    grp_fu_406_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_406_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_406_p_dout0 : IN STD_LOGIC_VECTOR (61 downto 0);
    grp_fu_406_p_ce : OUT STD_LOGIC );
end;


architecture behav of Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_66_8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv96_0 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv96_1 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal or_ln1027_1_reg_643 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_1_reg_643_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state13_io : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal icmp_ln1027_4_reg_607 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1027_4_fu_243_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem_blk_n_AR : STD_LOGIC;
    signal first_iter_2_reg_191 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal inputWidth_cast8_cast_fu_204_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal inputWidth_cast8_cast_reg_596 : STD_LOGIC_VECTOR (61 downto 0);
    signal inputHeight_cast7_cast_fu_208_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal inputHeight_cast7_cast_reg_601 : STD_LOGIC_VECTOR (61 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_4_reg_607_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_5_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_5_reg_611 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_5_reg_611_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_5_reg_611_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_5_reg_611_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_V_1_reg_622 : STD_LOGIC_VECTOR (16 downto 0);
    signal iChannel_V_1_reg_627 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1027_9_fu_305_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_9_reg_632 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_9_reg_632_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_9_reg_632_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln840_3_fu_311_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_3_reg_638 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln1027_1_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_1_reg_643_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_1_reg_643_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_1_reg_643_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_1_reg_643_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_1_reg_643_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_1_reg_643_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_1_reg_643_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_1_reg_643_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln67_1_fu_336_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln67_1_reg_647 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln186_fu_348_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_reg_652 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_reg_652_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal iChannel_V_1_cast15_fu_353_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln840_fu_361_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_reg_663 : STD_LOGIC_VECTOR (31 downto 0);
    signal iChannel_V_1_cast15_mid1_fu_410_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln67_1_fu_418_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln67_1_reg_673 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln67_1_reg_673_pp0_iter4_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln67_1_reg_673_pp0_iter5_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln67_1_reg_673_pp0_iter6_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln67_1_reg_673_pp0_iter7_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln67_1_reg_673_pp0_iter8_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln67_1_reg_673_pp0_iter9_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln67_1_reg_673_pp0_iter10_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln67_1_reg_673_pp0_iter11_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal empty_reg_678 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln186_1_fu_440_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_1_reg_683 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid143_reg_689 : STD_LOGIC_VECTOR (61 downto 0);
    signal select_ln1027_12_fu_476_p3 : STD_LOGIC_VECTOR (61 downto 0);
    signal select_ln1027_12_reg_694 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_483_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal mul_ln1027_reg_699 : STD_LOGIC_VECTOR (61 downto 0);
    signal sext_ln66_mid2_v_reg_704 : STD_LOGIC_VECTOR (61 downto 0);
    signal row_buffer_addr_reg_709 : STD_LOGIC_VECTOR (16 downto 0);
    signal row_buffer_addr_reg_709_pp0_iter13_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal row_buffer_addr_reg_709_pp0_iter14_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal row_buffer_addr_reg_709_pp0_iter15_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal row_buffer_addr_reg_709_pp0_iter16_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal row_buffer_addr_reg_709_pp0_iter17_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal row_buffer_addr_reg_709_pp0_iter18_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal row_buffer_addr_reg_709_pp0_iter19_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal gmem_addr_1_read_reg_724 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter5_stage0 : STD_LOGIC;
    signal ap_phi_mux_first_iter_2_phi_fu_196_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln67_fu_512_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln1027_fu_509_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_V_fu_100 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln840_4_fu_424_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_sig_allocacmp_x_V_1 : STD_LOGIC_VECTOR (16 downto 0);
    signal iChannel_V_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1027_11_fu_328_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten53_fu_108 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln1027_13_fu_265_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal cy_V_fu_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1027_6_fu_367_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten90_fu_116 : STD_LOGIC_VECTOR (95 downto 0);
    signal add_ln1027_fu_248_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal add_ln1027_3_fu_259_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_V_2_cast_fu_289_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1027_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_fu_298_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln1027_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln67_fu_374_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln1027_2_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_cast_fu_378_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln67_fu_397_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_fu_402_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1027_10_fu_390_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln186_cast_fu_444_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal select_ln1027_7_fu_455_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_cast_mid1_fu_452_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal empty_54_fu_447_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln1027_fu_460_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal p_mid145_fu_471_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal select_ln1027_8_fu_464_p3 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_483_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln66_mid2_v_v_v_v_fu_487_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1027_2_fu_494_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_356_ce : STD_LOGIC;
    signal grp_fu_413_ce : STD_LOGIC;
    signal grp_fu_483_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Conv2D_HW_mul_32ns_32ns_62_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component Conv2D_HW_mul_62s_32ns_62_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (61 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component Conv2D_HW_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_62s_32ns_62_5_1_U15 : component Conv2D_HW_mul_62s_32ns_62_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 62,
        din1_WIDTH => 32,
        dout_WIDTH => 62)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln1027_12_reg_694,
        din1 => grp_fu_483_p1,
        ce => grp_fu_483_ce,
        dout => grp_fu_483_p2);

    flow_control_loop_pipe_sequential_init_U : component Conv2D_HW_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter19_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter5_stage0)) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    cy_V_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    cy_V_fu_112 <= ap_const_lv32_0;
                elsif (((icmp_ln1027_4_reg_607_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    cy_V_fu_112 <= select_ln1027_6_fu_367_p3;
                end if;
            end if; 
        end if;
    end process;

    first_iter_2_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1027_4_reg_607_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                first_iter_2_reg_191 <= ap_const_lv1_0;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                first_iter_2_reg_191 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    iChannel_V_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    iChannel_V_fu_104 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln1027_4_reg_607 = ap_const_lv1_0))) then 
                    iChannel_V_fu_104 <= select_ln1027_11_fu_328_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten53_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten53_fu_108 <= ap_const_lv64_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1027_4_fu_243_p2 = ap_const_lv1_0))) then 
                    indvar_flatten53_fu_108 <= select_ln1027_13_fu_265_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten90_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten90_fu_116 <= ap_const_lv96_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln1027_4_fu_243_p2 = ap_const_lv1_0))) then 
                    indvar_flatten90_fu_116 <= add_ln1027_fu_248_p2;
                end if;
            end if; 
        end if;
    end process;

    x_V_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    x_V_fu_100 <= ap_const_lv17_0;
                elsif (((icmp_ln1027_4_reg_607_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    x_V_fu_100 <= add_ln840_4_fu_424_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1027_4_reg_607_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln186_1_reg_683 <= add_ln186_1_fu_440_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln186_reg_652 <= add_ln186_fu_348_p2;
                add_ln186_reg_652_pp0_iter4_reg <= add_ln186_reg_652;
                add_ln67_1_reg_673_pp0_iter10_reg <= add_ln67_1_reg_673_pp0_iter9_reg;
                add_ln67_1_reg_673_pp0_iter11_reg <= add_ln67_1_reg_673_pp0_iter10_reg;
                add_ln67_1_reg_673_pp0_iter4_reg <= add_ln67_1_reg_673;
                add_ln67_1_reg_673_pp0_iter5_reg <= add_ln67_1_reg_673_pp0_iter4_reg;
                add_ln67_1_reg_673_pp0_iter6_reg <= add_ln67_1_reg_673_pp0_iter5_reg;
                add_ln67_1_reg_673_pp0_iter7_reg <= add_ln67_1_reg_673_pp0_iter6_reg;
                add_ln67_1_reg_673_pp0_iter8_reg <= add_ln67_1_reg_673_pp0_iter7_reg;
                add_ln67_1_reg_673_pp0_iter9_reg <= add_ln67_1_reg_673_pp0_iter8_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                iChannel_V_1_reg_627 <= iChannel_V_fu_104;
                icmp_ln1027_4_reg_607_pp0_iter10_reg <= icmp_ln1027_4_reg_607_pp0_iter9_reg;
                icmp_ln1027_4_reg_607_pp0_iter11_reg <= icmp_ln1027_4_reg_607_pp0_iter10_reg;
                icmp_ln1027_4_reg_607_pp0_iter12_reg <= icmp_ln1027_4_reg_607_pp0_iter11_reg;
                icmp_ln1027_4_reg_607_pp0_iter13_reg <= icmp_ln1027_4_reg_607_pp0_iter12_reg;
                icmp_ln1027_4_reg_607_pp0_iter14_reg <= icmp_ln1027_4_reg_607_pp0_iter13_reg;
                icmp_ln1027_4_reg_607_pp0_iter15_reg <= icmp_ln1027_4_reg_607_pp0_iter14_reg;
                icmp_ln1027_4_reg_607_pp0_iter16_reg <= icmp_ln1027_4_reg_607_pp0_iter15_reg;
                icmp_ln1027_4_reg_607_pp0_iter17_reg <= icmp_ln1027_4_reg_607_pp0_iter16_reg;
                icmp_ln1027_4_reg_607_pp0_iter18_reg <= icmp_ln1027_4_reg_607_pp0_iter17_reg;
                icmp_ln1027_4_reg_607_pp0_iter19_reg <= icmp_ln1027_4_reg_607_pp0_iter18_reg;
                icmp_ln1027_4_reg_607_pp0_iter2_reg <= icmp_ln1027_4_reg_607;
                icmp_ln1027_4_reg_607_pp0_iter3_reg <= icmp_ln1027_4_reg_607_pp0_iter2_reg;
                icmp_ln1027_4_reg_607_pp0_iter4_reg <= icmp_ln1027_4_reg_607_pp0_iter3_reg;
                icmp_ln1027_4_reg_607_pp0_iter5_reg <= icmp_ln1027_4_reg_607_pp0_iter4_reg;
                icmp_ln1027_4_reg_607_pp0_iter6_reg <= icmp_ln1027_4_reg_607_pp0_iter5_reg;
                icmp_ln1027_4_reg_607_pp0_iter7_reg <= icmp_ln1027_4_reg_607_pp0_iter6_reg;
                icmp_ln1027_4_reg_607_pp0_iter8_reg <= icmp_ln1027_4_reg_607_pp0_iter7_reg;
                icmp_ln1027_4_reg_607_pp0_iter9_reg <= icmp_ln1027_4_reg_607_pp0_iter8_reg;
                icmp_ln1027_5_reg_611_pp0_iter2_reg <= icmp_ln1027_5_reg_611;
                icmp_ln1027_5_reg_611_pp0_iter3_reg <= icmp_ln1027_5_reg_611_pp0_iter2_reg;
                icmp_ln1027_5_reg_611_pp0_iter4_reg <= icmp_ln1027_5_reg_611_pp0_iter3_reg;
                mul_ln1027_reg_699 <= grp_fu_483_p2;
                or_ln1027_1_reg_643_pp0_iter10_reg <= or_ln1027_1_reg_643_pp0_iter9_reg;
                or_ln1027_1_reg_643_pp0_iter11_reg <= or_ln1027_1_reg_643_pp0_iter10_reg;
                or_ln1027_1_reg_643_pp0_iter3_reg <= or_ln1027_1_reg_643;
                or_ln1027_1_reg_643_pp0_iter4_reg <= or_ln1027_1_reg_643_pp0_iter3_reg;
                or_ln1027_1_reg_643_pp0_iter5_reg <= or_ln1027_1_reg_643_pp0_iter4_reg;
                or_ln1027_1_reg_643_pp0_iter6_reg <= or_ln1027_1_reg_643_pp0_iter5_reg;
                or_ln1027_1_reg_643_pp0_iter7_reg <= or_ln1027_1_reg_643_pp0_iter6_reg;
                or_ln1027_1_reg_643_pp0_iter8_reg <= or_ln1027_1_reg_643_pp0_iter7_reg;
                or_ln1027_1_reg_643_pp0_iter9_reg <= or_ln1027_1_reg_643_pp0_iter8_reg;
                row_buffer_addr_reg_709 <= zext_ln67_fu_512_p1(17 - 1 downto 0);
                row_buffer_addr_reg_709_pp0_iter13_reg <= row_buffer_addr_reg_709;
                row_buffer_addr_reg_709_pp0_iter14_reg <= row_buffer_addr_reg_709_pp0_iter13_reg;
                row_buffer_addr_reg_709_pp0_iter15_reg <= row_buffer_addr_reg_709_pp0_iter14_reg;
                row_buffer_addr_reg_709_pp0_iter16_reg <= row_buffer_addr_reg_709_pp0_iter15_reg;
                row_buffer_addr_reg_709_pp0_iter17_reg <= row_buffer_addr_reg_709_pp0_iter16_reg;
                row_buffer_addr_reg_709_pp0_iter18_reg <= row_buffer_addr_reg_709_pp0_iter17_reg;
                row_buffer_addr_reg_709_pp0_iter19_reg <= row_buffer_addr_reg_709_pp0_iter18_reg;
                select_ln1027_9_reg_632_pp0_iter3_reg <= select_ln1027_9_reg_632;
                select_ln1027_9_reg_632_pp0_iter4_reg <= select_ln1027_9_reg_632_pp0_iter3_reg;
                sext_ln66_mid2_v_reg_704 <= add_ln1027_2_fu_494_p2(63 downto 2);
                x_V_1_reg_622 <= ap_sig_allocacmp_x_V_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1027_4_reg_607_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln67_1_reg_673 <= add_ln67_1_fu_418_p2;
                add_ln840_reg_663 <= add_ln840_fu_361_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_4_reg_607 = ap_const_lv1_0))) then
                add_ln840_3_reg_638 <= add_ln840_3_fu_311_p2;
                or_ln1027_1_reg_643 <= or_ln1027_1_fu_322_p2;
                select_ln1027_9_reg_632 <= select_ln1027_9_fu_305_p3;
                trunc_ln67_1_reg_647 <= trunc_ln67_1_fu_336_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln1027_4_reg_607 <= icmp_ln1027_4_fu_243_p2;
                    inputHeight_cast7_cast_reg_601(31 downto 0) <= inputHeight_cast7_cast_fu_208_p1(31 downto 0);
                    inputWidth_cast8_cast_reg_596(31 downto 0) <= inputWidth_cast8_cast_fu_204_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln1027_9_reg_632_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln1027_5_reg_611_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                empty_reg_678 <= grp_fu_400_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_4_reg_607_pp0_iter18_reg = ap_const_lv1_0))) then
                gmem_addr_1_read_reg_724 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1027_4_fu_243_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln1027_5_reg_611 <= icmp_ln1027_5_fu_254_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln1027_9_reg_632_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln1027_4_reg_607_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_mid143_reg_689 <= grp_fu_406_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1027_4_reg_607_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln1027_12_reg_694 <= select_ln1027_12_fu_476_p3;
            end if;
        end if;
    end process;
    inputWidth_cast8_cast_reg_596(61 downto 32) <= "000000000000000000000000000000";
    inputHeight_cast7_cast_reg_601(61 downto 32) <= "000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1027_2_fu_494_p2 <= std_logic_vector(unsigned(sext_ln66_mid2_v_v_v_v_fu_487_p3) + unsigned(input_r));
    add_ln1027_3_fu_259_p2 <= std_logic_vector(unsigned(indvar_flatten53_fu_108) + unsigned(ap_const_lv64_1));
    add_ln1027_fu_248_p2 <= std_logic_vector(unsigned(indvar_flatten90_fu_116) + unsigned(ap_const_lv96_1));
    add_ln186_1_fu_440_p2 <= std_logic_vector(unsigned(add_ln840_reg_663) + unsigned(y_V));
    add_ln186_cast_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln186_reg_652_pp0_iter4_reg),62));
    add_ln186_cast_mid1_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln186_1_reg_683),62));
    add_ln186_fu_348_p2 <= std_logic_vector(unsigned(cy_V_fu_112) + unsigned(y_V));
    add_ln67_1_fu_418_p2 <= std_logic_vector(unsigned(tmp_6_fu_402_p3) + unsigned(select_ln1027_10_fu_390_p3));
    add_ln67_fu_397_p2 <= std_logic_vector(unsigned(tmp_4_cast_fu_378_p3) + unsigned(trunc_ln67_1_reg_647));
    add_ln840_3_fu_311_p2 <= std_logic_vector(unsigned(select_ln1027_fu_298_p3) + unsigned(ap_const_lv32_1));
    add_ln840_4_fu_424_p2 <= std_logic_vector(unsigned(select_ln1027_10_fu_390_p3) + unsigned(ap_const_lv17_1));
    add_ln840_fu_361_p2 <= std_logic_vector(unsigned(cy_V_fu_112) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter19, m_axi_gmem_RVALID, ap_block_state13_io, icmp_ln1027_4_reg_607_pp0_iter18_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter19 = ap_const_logic_1) and (icmp_ln1027_4_reg_607_pp0_iter18_reg = ap_const_lv1_0) and (m_axi_gmem_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter19, m_axi_gmem_RVALID, ap_block_state13_io, icmp_ln1027_4_reg_607_pp0_iter18_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter19 = ap_const_logic_1) and (icmp_ln1027_4_reg_607_pp0_iter18_reg = ap_const_lv1_0) and (m_axi_gmem_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_io)));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state13_io_assign_proc : process(m_axi_gmem_ARREADY, or_ln1027_1_reg_643_pp0_iter11_reg)
    begin
                ap_block_state13_io <= ((or_ln1027_1_reg_643_pp0_iter11_reg = ap_const_lv1_1) and (m_axi_gmem_ARREADY = ap_const_logic_0));
    end process;

        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state20_pp0_stage0_iter19_assign_proc : process(m_axi_gmem_RVALID, icmp_ln1027_4_reg_607_pp0_iter18_reg)
    begin
                ap_block_state20_pp0_stage0_iter19 <= ((icmp_ln1027_4_reg_607_pp0_iter18_reg = ap_const_lv1_0) and (m_axi_gmem_RVALID = ap_const_logic_0));
    end process;

        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln1027_4_fu_243_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1027_4_fu_243_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter5_stage0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_subdone, icmp_ln1027_4_reg_607_pp0_iter4_reg)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln1027_4_reg_607_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter5_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter5_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter19_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter19_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20)
    begin
        if (((ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_first_iter_2_phi_fu_196_p4_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, first_iter_2_reg_191, icmp_ln1027_4_reg_607_pp0_iter2_reg)
    begin
        if (((icmp_ln1027_4_reg_607_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_first_iter_2_phi_fu_196_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_2_phi_fu_196_p4 <= first_iter_2_reg_191;
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_V_1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, icmp_ln1027_4_reg_607_pp0_iter2_reg, x_V_fu_100, add_ln840_4_fu_424_p2)
    begin
        if (((icmp_ln1027_4_reg_607_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_x_V_1 <= add_ln840_4_fu_424_p2;
        else 
            ap_sig_allocacmp_x_V_1 <= x_V_fu_100;
        end if; 
    end process;

    empty_54_fu_447_p2 <= std_logic_vector(unsigned(empty_reg_678) + unsigned(add_ln186_cast_fu_444_p1));

    gmem_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter12, m_axi_gmem_ARREADY, or_ln1027_1_reg_643_pp0_iter11_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln1027_1_reg_643_pp0_iter11_reg = ap_const_lv1_1))) then 
            gmem_blk_n_AR <= m_axi_gmem_ARREADY;
        else 
            gmem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter19, m_axi_gmem_RVALID, icmp_ln1027_4_reg_607_pp0_iter18_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter19 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1027_4_reg_607_pp0_iter18_reg = ap_const_lv1_0))) then 
            gmem_blk_n_R <= m_axi_gmem_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_356_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_356_ce <= ap_const_logic_1;
        else 
            grp_fu_356_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_400_p_ce <= grp_fu_356_ce;
    grp_fu_400_p_din0 <= iChannel_V_1_cast15_fu_353_p1(32 - 1 downto 0);
    grp_fu_400_p_din1 <= inputHeight_cast7_cast_reg_601(32 - 1 downto 0);
    grp_fu_406_p_ce <= grp_fu_413_ce;
    grp_fu_406_p_din0 <= iChannel_V_1_cast15_mid1_fu_410_p1(32 - 1 downto 0);
    grp_fu_406_p_din1 <= inputHeight_cast7_cast_reg_601(32 - 1 downto 0);

    grp_fu_413_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_413_ce <= ap_const_logic_1;
        else 
            grp_fu_413_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_483_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_483_ce <= ap_const_logic_1;
        else 
            grp_fu_483_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_483_p1 <= inputWidth_cast8_cast_reg_596(32 - 1 downto 0);
    iChannel_V_1_cast15_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(iChannel_V_1_reg_627),62));
    iChannel_V_1_cast15_mid1_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln840_3_reg_638),62));
    icmp_ln1027_4_fu_243_p2 <= "1" when (indvar_flatten90_fu_116 = mul_ln17_3) else "0";
    icmp_ln1027_5_fu_254_p2 <= "1" when (indvar_flatten53_fu_108 = mul_ln17_2) else "0";
    icmp_ln1027_fu_293_p2 <= "1" when (x_V_2_cast_fu_289_p1 = inputWidth) else "0";
    inputHeight_cast7_cast_fu_208_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(inputHeight_cast7),62));
    inputWidth_cast8_cast_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(inputWidth_cast8),62));
    m_axi_gmem_ARADDR <= sext_ln1027_fu_509_p1;
    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= inputWidth;
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;

    m_axi_gmem_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter12, or_ln1027_1_reg_643_pp0_iter11_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln1027_1_reg_643_pp0_iter11_reg = ap_const_lv1_1))) then 
            m_axi_gmem_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_AWID <= ap_const_lv1_0;
    m_axi_gmem_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_AWVALID <= ap_const_logic_0;
    m_axi_gmem_BREADY <= ap_const_logic_0;

    m_axi_gmem_RREADY_assign_proc : process(ap_enable_reg_pp0_iter19, icmp_ln1027_4_reg_607_pp0_iter18_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter19 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1027_4_reg_607_pp0_iter18_reg = ap_const_lv1_0))) then 
            m_axi_gmem_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_WDATA <= ap_const_lv32_0;
    m_axi_gmem_WID <= ap_const_lv1_0;
    m_axi_gmem_WLAST <= ap_const_logic_0;
    m_axi_gmem_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_WUSER <= ap_const_lv1_0;
    m_axi_gmem_WVALID <= ap_const_logic_0;
    or_ln1027_1_fu_322_p2 <= (select_ln1027_9_fu_305_p3 or or_ln1027_fu_317_p2);
    or_ln1027_2_fu_386_p2 <= (select_ln1027_9_reg_632 or icmp_ln1027_5_reg_611_pp0_iter2_reg);
    or_ln1027_fu_317_p2 <= (icmp_ln1027_5_reg_611 or ap_phi_mux_first_iter_2_phi_fu_196_p4);
    p_mid145_fu_471_p2 <= std_logic_vector(unsigned(p_mid143_reg_689) + unsigned(zext_ln1027_fu_460_p1));
    row_buffer_address0 <= row_buffer_addr_reg_709_pp0_iter19_reg;

    row_buffer_ce0_assign_proc : process(ap_enable_reg_pp0_iter20, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter20 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            row_buffer_ce0 <= ap_const_logic_1;
        else 
            row_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    row_buffer_d0 <= gmem_addr_1_read_reg_724;

    row_buffer_we0_assign_proc : process(ap_enable_reg_pp0_iter20, ap_block_pp0_stage0_11001, icmp_ln1027_4_reg_607_pp0_iter19_reg)
    begin
        if (((ap_enable_reg_pp0_iter20 = ap_const_logic_1) and (icmp_ln1027_4_reg_607_pp0_iter19_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            row_buffer_we0 <= ap_const_logic_1;
        else 
            row_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln1027_10_fu_390_p3 <= 
        ap_const_lv17_0 when (or_ln1027_2_fu_386_p2(0) = '1') else 
        x_V_1_reg_622;
    select_ln1027_11_fu_328_p3 <= 
        add_ln840_3_fu_311_p2 when (select_ln1027_9_fu_305_p3(0) = '1') else 
        select_ln1027_fu_298_p3;
    select_ln1027_12_fu_476_p3 <= 
        p_mid145_fu_471_p2 when (select_ln1027_9_reg_632_pp0_iter4_reg(0) = '1') else 
        select_ln1027_8_fu_464_p3;
    select_ln1027_13_fu_265_p3 <= 
        ap_const_lv64_1 when (icmp_ln1027_5_fu_254_p2(0) = '1') else 
        add_ln1027_3_fu_259_p2;
    select_ln1027_6_fu_367_p3 <= 
        add_ln840_fu_361_p2 when (icmp_ln1027_5_reg_611_pp0_iter2_reg(0) = '1') else 
        cy_V_fu_112;
    select_ln1027_7_fu_455_p3 <= 
        add_ln186_1_reg_683 when (icmp_ln1027_5_reg_611_pp0_iter4_reg(0) = '1') else 
        add_ln186_reg_652_pp0_iter4_reg;
    select_ln1027_8_fu_464_p3 <= 
        add_ln186_cast_mid1_fu_452_p1 when (icmp_ln1027_5_reg_611_pp0_iter4_reg(0) = '1') else 
        empty_54_fu_447_p2;
    select_ln1027_9_fu_305_p3 <= 
        icmp_ln1027_3 when (icmp_ln1027_5_reg_611(0) = '1') else 
        icmp_ln1027_fu_293_p2;
    select_ln1027_fu_298_p3 <= 
        ap_const_lv32_0 when (icmp_ln1027_5_reg_611(0) = '1') else 
        iChannel_V_fu_104;
        sext_ln1027_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln66_mid2_v_reg_704),64));

    sext_ln66_mid2_v_v_v_v_fu_487_p3 <= (mul_ln1027_reg_699 & ap_const_lv2_0);
    tmp_4_cast_fu_378_p3 <= (trunc_ln67_fu_374_p1 & ap_const_lv8_0);
    tmp_6_fu_402_p3 <= (add_ln67_fu_397_p2 & ap_const_lv7_0);
    trunc_ln67_1_fu_336_p1 <= select_ln1027_11_fu_328_p3(10 - 1 downto 0);
    trunc_ln67_fu_374_p1 <= select_ln1027_6_fu_367_p3(2 - 1 downto 0);
    x_V_2_cast_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_x_V_1),32));
    zext_ln1027_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1027_7_fu_455_p3),62));
    zext_ln67_fu_512_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln67_1_reg_673_pp0_iter11_reg),64));
end behav;
