// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Conv2D_HW_Conv2D_HW,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=264,HLS_SYN_DSP=0,HLS_SYN_FF=9549,HLS_SYN_LUT=8731,HLS_VERSION=2022_2}" *)

module Conv2D_HW (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 34'd1;
parameter    ap_ST_fsm_state2 = 34'd2;
parameter    ap_ST_fsm_state3 = 34'd4;
parameter    ap_ST_fsm_state4 = 34'd8;
parameter    ap_ST_fsm_state5 = 34'd16;
parameter    ap_ST_fsm_state6 = 34'd32;
parameter    ap_ST_fsm_state7 = 34'd64;
parameter    ap_ST_fsm_state8 = 34'd128;
parameter    ap_ST_fsm_state9 = 34'd256;
parameter    ap_ST_fsm_state10 = 34'd512;
parameter    ap_ST_fsm_state11 = 34'd1024;
parameter    ap_ST_fsm_state12 = 34'd2048;
parameter    ap_ST_fsm_state13 = 34'd4096;
parameter    ap_ST_fsm_state14 = 34'd8192;
parameter    ap_ST_fsm_state15 = 34'd16384;
parameter    ap_ST_fsm_state16 = 34'd32768;
parameter    ap_ST_fsm_state17 = 34'd65536;
parameter    ap_ST_fsm_state18 = 34'd131072;
parameter    ap_ST_fsm_state19 = 34'd262144;
parameter    ap_ST_fsm_state20 = 34'd524288;
parameter    ap_ST_fsm_state21 = 34'd1048576;
parameter    ap_ST_fsm_state22 = 34'd2097152;
parameter    ap_ST_fsm_state23 = 34'd4194304;
parameter    ap_ST_fsm_state24 = 34'd8388608;
parameter    ap_ST_fsm_state25 = 34'd16777216;
parameter    ap_ST_fsm_state26 = 34'd33554432;
parameter    ap_ST_fsm_state27 = 34'd67108864;
parameter    ap_ST_fsm_state28 = 34'd134217728;
parameter    ap_ST_fsm_state29 = 34'd268435456;
parameter    ap_ST_fsm_state30 = 34'd536870912;
parameter    ap_ST_fsm_state31 = 34'd1073741824;
parameter    ap_ST_fsm_state32 = 34'd2147483648;
parameter    ap_ST_fsm_state33 = 34'd4294967296;
parameter    ap_ST_fsm_state34 = 34'd8589934592;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [33:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_r;
wire   [63:0] output_r;
wire   [63:0] coeffs;
wire   [63:0] biases;
wire   [31:0] numChannels;
wire   [31:0] numFilters;
wire   [31:0] inputWidth;
wire   [31:0] inputHeight;
wire   [31:0] convWidth;
wire   [31:0] convHeight;
wire   [0:0] apply_relu;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state18;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state25;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state23;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state29;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state34;
reg   [0:0] apply_relu_read_reg_713;
reg   [31:0] convHeight_read_reg_718;
reg   [31:0] convWidth_read_reg_726;
reg   [31:0] inputHeight_read_reg_736;
reg   [31:0] inputWidth_read_reg_742;
reg   [31:0] numFilters_read_reg_753;
reg   [31:0] numChannels_read_reg_758;
reg   [63:0] biases_read_reg_765;
reg   [63:0] coeffs_read_reg_770;
reg   [63:0] output_r_read_reg_775;
reg   [63:0] input_r_read_reg_780;
wire    ap_CS_fsm_state2;
wire   [63:0] grp_fu_344_p2;
reg   [63:0] mul_ln17_reg_811;
wire    ap_CS_fsm_state3;
wire   [63:0] grp_fu_356_p2;
reg   [63:0] mul_ln17_2_reg_818;
wire    ap_CS_fsm_state4;
wire   [61:0] numChannels_cast_fu_386_p1;
wire    ap_CS_fsm_state6;
wire   [61:0] convHeight_cast_fu_389_p1;
wire   [61:0] convWidth_cast_fu_392_p1;
reg   [61:0] convWidth_cast_reg_855;
wire   [0:0] cmp_i5741286_fu_395_p2;
reg   [0:0] cmp_i5741286_reg_861;
wire   [61:0] grp_fu_400_p2;
reg   [61:0] mul_ln38_reg_866;
wire    ap_CS_fsm_state7;
wire  signed [61:0] grp_fu_406_p2;
reg  signed [61:0] mul_ln39_reg_872;
wire  signed [32:0] sub_i_i399_fu_415_p2;
reg  signed [32:0] sub_i_i399_reg_877;
wire    ap_CS_fsm_state8;
wire   [32:0] sub_i_i228_fu_424_p2;
reg   [32:0] sub_i_i228_reg_882;
wire  signed [63:0] sext_ln43_fu_441_p1;
reg  signed [63:0] sext_ln43_reg_887;
wire   [31:0] empty_fu_456_p3;
reg   [31:0] empty_reg_892;
wire  signed [63:0] sext_ln73_1_fu_480_p1;
reg  signed [63:0] sext_ln73_1_reg_897;
wire   [31:0] empty_57_fu_489_p3;
reg   [31:0] empty_57_reg_902;
wire   [95:0] grp_fu_368_p2;
reg   [95:0] mul_ln17_1_reg_907;
wire   [95:0] grp_fu_380_p2;
reg   [95:0] mul_ln17_3_reg_913;
wire   [0:0] icmp_ln1027_1_fu_497_p2;
reg   [0:0] icmp_ln1027_1_reg_918;
wire   [0:0] icmp_ln1027_3_fu_502_p2;
reg   [0:0] icmp_ln1027_3_reg_924;
wire   [61:0] add_ln1027_fu_516_p2;
reg   [61:0] add_ln1027_reg_935;
wire    ap_CS_fsm_state9;
wire   [63:0] add_ln1027_4_fu_521_p2;
reg   [63:0] add_ln1027_4_reg_940;
wire   [31:0] add_ln840_fu_531_p2;
reg   [31:0] add_ln840_reg_948;
reg   [63:0] gmem_addr_reg_953;
wire   [0:0] icmp_ln1027_fu_526_p2;
wire   [61:0] grp_fu_537_p2;
reg   [61:0] mul_ln39_1_reg_959;
wire    ap_CS_fsm_state13;
wire   [31:0] y_V_1_fu_588_p2;
reg   [31:0] y_V_1_reg_967;
wire    ap_CS_fsm_state16;
wire  signed [63:0] tmp_fu_598_p2;
reg  signed [63:0] tmp_reg_972;
wire   [0:0] icmp_ln1027_2_fu_583_p2;
wire   [63:0] grp_fu_615_p2;
reg   [63:0] mul_ln58_reg_977;
wire    ap_CS_fsm_state21;
reg   [63:0] gmem_addr_2_reg_982;
wire    ap_CS_fsm_state22;
reg   [31:0] gmem_addr_read_reg_988;
wire   [31:0] x_V_2_fu_652_p2;
reg   [31:0] x_V_2_reg_996;
wire    ap_CS_fsm_state26;
wire   [16:0] trunc_ln77_fu_658_p1;
reg   [16:0] trunc_ln77_reg_1001;
wire   [0:0] icmp_ln1027_6_fu_647_p2;
wire   [31:0] acc_2_fu_684_p3;
reg   [31:0] acc_2_reg_1006;
wire    ap_CS_fsm_state28;
reg   [11:0] coeff_cache_address0;
reg    coeff_cache_ce0;
reg    coeff_cache_we0;
wire   [31:0] coeff_cache_q0;
reg   [16:0] row_buffer_address0;
reg    row_buffer_ce0;
reg    row_buffer_we0;
wire   [31:0] row_buffer_q0;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_start;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_done;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_idle;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_ready;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WVALID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WDATA;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WSTRB;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WLAST;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WID;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_RREADY;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_BREADY;
wire   [11:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_address0;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_ce0;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_d0;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_start;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_done;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_idle;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_ready;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WVALID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WDATA;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WSTRB;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WLAST;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WID;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_RREADY;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_BREADY;
wire   [16:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_address0;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_ce0;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_d0;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_400_p_din0;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_400_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_400_p_ce;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_406_p_din0;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_406_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_406_p_ce;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_start;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_done;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_idle;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_ready;
wire   [11:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_coeff_cache_address0;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_coeff_cache_ce0;
wire   [16:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_row_buffer_address0;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_row_buffer_ce0;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_acc_2_out;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_acc_2_out_ap_vld;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg   [31:0] y_V_reg_257;
wire    ap_CS_fsm_state15;
reg   [31:0] x_V_reg_269;
reg    grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_start_reg;
reg   [33:0] ap_NS_fsm;
wire    ap_NS_fsm_state14;
wire    ap_CS_fsm_state14;
reg    grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_start_reg;
wire    ap_CS_fsm_state17;
reg    grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_start_reg;
wire    ap_CS_fsm_state27;
wire  signed [63:0] p_cast_cast_fu_569_p1;
wire  signed [63:0] sext_ln73_fu_633_p1;
reg  signed [61:0] phi_mul147_fu_140;
reg   [63:0] phi_mul_fu_144;
reg   [31:0] iFilter_V_fu_148;
wire   [31:0] grp_fu_344_p0;
wire   [31:0] grp_fu_344_p1;
wire   [31:0] grp_fu_356_p0;
wire   [31:0] grp_fu_356_p1;
wire   [31:0] grp_fu_368_p0;
wire   [63:0] grp_fu_368_p1;
wire   [31:0] grp_fu_380_p0;
wire   [63:0] grp_fu_380_p1;
reg   [31:0] grp_fu_400_p0;
reg   [31:0] grp_fu_400_p1;
reg   [31:0] grp_fu_406_p0;
reg   [31:0] grp_fu_406_p1;
wire   [32:0] inputHeight_cast_fu_412_p1;
wire   [32:0] inputWidth_cast_fu_421_p1;
wire   [0:0] cmp_i5691284_fu_430_p2;
wire   [31:0] trunc_ln43_fu_445_p1;
wire   [31:0] select_ln43_fu_448_p3;
wire   [33:0] shl_ln_fu_463_p3;
wire   [34:0] zext_ln58_1_fu_470_p1;
wire   [34:0] add_ln58_fu_474_p2;
wire   [0:0] cmp_i2051307_fu_435_p2;
wire   [31:0] add_ln73_fu_484_p2;
wire  signed [61:0] add_ln1027_fu_516_p0;
wire   [33:0] tmp_1_fu_542_p3;
wire   [63:0] p_cast11_fu_550_p1;
wire   [63:0] empty_58_fu_554_p2;
wire   [61:0] p_cast_fu_559_p4;
wire   [32:0] zext_ln1027_fu_579_p1;
wire   [63:0] zext_ln58_fu_594_p1;
wire  signed [34:0] grp_fu_615_p1;
wire   [63:0] add_ln58_1_fu_619_p2;
wire   [61:0] trunc_ln1_fu_623_p4;
wire   [32:0] zext_ln1027_1_fu_643_p1;
wire   [31:0] acc_fu_666_p2;
wire   [0:0] tmp_2_fu_671_p3;
wire   [0:0] and_ln96_fu_679_p2;
reg    grp_fu_400_ce;
reg    grp_fu_406_ce;
reg    grp_fu_615_ce;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
reg    ap_ST_fsm_state34_blk;
wire   [63:0] grp_fu_344_p00;
wire   [63:0] grp_fu_344_p10;
wire   [63:0] grp_fu_356_p00;
wire   [63:0] grp_fu_356_p10;
wire   [95:0] grp_fu_368_p00;
wire   [95:0] grp_fu_368_p10;
wire   [95:0] grp_fu_380_p00;
wire   [95:0] grp_fu_380_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 34'd1;
#0 grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_start_reg = 1'b0;
#0 grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_start_reg = 1'b0;
#0 grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_start_reg = 1'b0;
end

Conv2D_HW_coeff_cache_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2304 ),
    .AddressWidth( 12 ))
coeff_cache_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(coeff_cache_address0),
    .ce0(coeff_cache_ce0),
    .we0(coeff_cache_we0),
    .d0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_d0),
    .q0(coeff_cache_q0)
);

Conv2D_HW_row_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 98304 ),
    .AddressWidth( 17 ))
row_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(row_buffer_address0),
    .ce0(row_buffer_ce0),
    .we0(row_buffer_we0),
    .d0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_d0),
    .q0(row_buffer_q0)
);

Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_44_4 grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_start),
    .ap_done(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_done),
    .ap_idle(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_idle),
    .ap_ready(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_ready),
    .m_axi_gmem_AWVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .convWidth(convWidth_read_reg_726),
    .mul_ln17_1(mul_ln17_1_reg_907),
    .empty(empty_reg_892),
    .mul_ln17(mul_ln17_reg_811),
    .mul_ln38(mul_ln38_reg_866),
    .mul_ln39_3(mul_ln39_1_reg_959),
    .coeffs(coeffs_read_reg_770),
    .icmp_ln1027_1(icmp_ln1027_1_reg_918),
    .coeff_cache_address0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_address0),
    .coeff_cache_ce0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_ce0),
    .coeff_cache_we0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_we0),
    .coeff_cache_d0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_d0)
);

Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_66_8 grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_start),
    .ap_done(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_done),
    .ap_idle(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_idle),
    .ap_ready(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_ready),
    .m_axi_gmem_AWVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .y_V(y_V_reg_257),
    .inputHeight_cast7(inputHeight_read_reg_736),
    .inputWidth(inputWidth_read_reg_742),
    .mul_ln17_3(mul_ln17_3_reg_913),
    .mul_ln17_2(mul_ln17_2_reg_818),
    .icmp_ln1027_3(icmp_ln1027_3_reg_924),
    .inputWidth_cast8(inputWidth_read_reg_742),
    .input_r(input_r_read_reg_780),
    .row_buffer_address0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_address0),
    .row_buffer_ce0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_ce0),
    .row_buffer_we0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_we0),
    .row_buffer_d0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_d0),
    .grp_fu_400_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_400_p_din0),
    .grp_fu_400_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_400_p_din1),
    .grp_fu_400_p_dout0(grp_fu_400_p2),
    .grp_fu_400_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_400_p_ce),
    .grp_fu_406_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_406_p_din0),
    .grp_fu_406_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_406_p_din1),
    .grp_fu_406_p_dout0(grp_fu_406_p2),
    .grp_fu_406_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_406_p_ce)
);

Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12 grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_start),
    .ap_done(grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_done),
    .ap_idle(grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_idle),
    .ap_ready(grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_ready),
    .mul_ln17_1(mul_ln17_1_reg_907),
    .mul_ln17(mul_ln17_reg_811),
    .convWidth(convWidth_read_reg_726),
    .icmp_ln1027_1(icmp_ln1027_1_reg_918),
    .coeff_cache_address0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_coeff_cache_address0),
    .coeff_cache_ce0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_coeff_cache_ce0),
    .coeff_cache_q0(coeff_cache_q0),
    .trunc_ln2(trunc_ln77_reg_1001),
    .row_buffer_address0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_row_buffer_address0),
    .row_buffer_ce0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_row_buffer_ce0),
    .row_buffer_q0(row_buffer_q0),
    .acc_2_out(grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_acc_2_out),
    .acc_2_out_ap_vld(grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_acc_2_out_ap_vld)
);

Conv2D_HW_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .output_r(output_r),
    .coeffs(coeffs),
    .biases(biases),
    .numChannels(numChannels),
    .numFilters(numFilters),
    .inputWidth(inputWidth),
    .inputHeight(inputHeight),
    .convWidth(convWidth),
    .convHeight(convHeight),
    .apply_relu(apply_relu),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

Conv2D_HW_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_2_reg_982),
    .I_AWLEN(empty_57_reg_902),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(acc_2_reg_1006),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

Conv2D_HW_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U37(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_344_p0),
    .din1(grp_fu_344_p1),
    .ce(1'b1),
    .dout(grp_fu_344_p2)
);

Conv2D_HW_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U38(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_356_p0),
    .din1(grp_fu_356_p1),
    .ce(1'b1),
    .dout(grp_fu_356_p2)
);

Conv2D_HW_mul_32ns_64ns_96_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 96 ))
mul_32ns_64ns_96_5_1_U39(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_368_p0),
    .din1(grp_fu_368_p1),
    .ce(1'b1),
    .dout(grp_fu_368_p2)
);

Conv2D_HW_mul_32ns_64ns_96_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 96 ))
mul_32ns_64ns_96_5_1_U40(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_380_p0),
    .din1(grp_fu_380_p1),
    .ce(1'b1),
    .dout(grp_fu_380_p2)
);

Conv2D_HW_mul_32ns_32ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 62 ))
mul_32ns_32ns_62_2_1_U41(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_400_p0),
    .din1(grp_fu_400_p1),
    .ce(grp_fu_400_ce),
    .dout(grp_fu_400_p2)
);

Conv2D_HW_mul_32ns_32ns_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 62 ))
mul_32ns_32ns_62_2_1_U42(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_406_p0),
    .din1(grp_fu_406_p1),
    .ce(grp_fu_406_ce),
    .dout(grp_fu_406_p2)
);

Conv2D_HW_mul_62s_62s_62_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 62 ),
    .din1_WIDTH( 62 ),
    .dout_WIDTH( 62 ))
mul_62s_62s_62_5_1_U43(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(mul_ln39_reg_872),
    .din1(phi_mul147_fu_140),
    .ce(1'b1),
    .dout(grp_fu_537_p2)
);

Conv2D_HW_mul_64s_35s_64_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 35 ),
    .dout_WIDTH( 64 ))
mul_64s_35s_64_5_1_U44(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(tmp_reg_972),
    .din1(grp_fu_615_p1),
    .ce(grp_fu_615_ce),
    .dout(grp_fu_615_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state14) & (1'b1 == ap_CS_fsm_state13))) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_start_reg <= 1'b1;
        end else if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_ready == 1'b1)) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1027_2_fu_583_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_start_reg <= 1'b1;
        end else if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_ready == 1'b1)) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1027_6_fu_647_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_start_reg <= 1'b1;
        end else if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_ready == 1'b1)) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        iFilter_V_fu_148 <= 32'd0;
    end else if (((icmp_ln1027_2_fu_583_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        iFilter_V_fu_148 <= add_ln840_reg_948;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul147_fu_140 <= 62'd0;
    end else if (((icmp_ln1027_2_fu_583_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        phi_mul147_fu_140 <= add_ln1027_reg_935;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_fu_144 <= 64'd0;
    end else if (((icmp_ln1027_2_fu_583_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        phi_mul_fu_144 <= add_ln1027_4_reg_940;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        x_V_reg_269 <= x_V_2_reg_996;
    end else if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        x_V_reg_269 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        y_V_reg_257 <= 32'd0;
    end else if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
        y_V_reg_257 <= y_V_1_reg_967;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        acc_2_reg_1006 <= acc_2_fu_684_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln1027_4_reg_940 <= add_ln1027_4_fu_521_p2;
        add_ln1027_reg_935 <= add_ln1027_fu_516_p2;
        add_ln840_reg_948 <= add_ln840_fu_531_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        apply_relu_read_reg_713 <= apply_relu;
        biases_read_reg_765 <= biases;
        coeffs_read_reg_770 <= coeffs;
        convHeight_read_reg_718 <= convHeight;
        convWidth_read_reg_726 <= convWidth;
        inputHeight_read_reg_736 <= inputHeight;
        inputWidth_read_reg_742 <= inputWidth;
        input_r_read_reg_780 <= input_r;
        numChannels_read_reg_758 <= numChannels;
        numFilters_read_reg_753 <= numFilters;
        output_r_read_reg_775 <= output_r;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        cmp_i5741286_reg_861 <= cmp_i5741286_fu_395_p2;
        convWidth_cast_reg_855[31 : 0] <= convWidth_cast_fu_392_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        empty_57_reg_902 <= empty_57_fu_489_p3;
        empty_reg_892 <= empty_fu_456_p3;
        icmp_ln1027_1_reg_918 <= icmp_ln1027_1_fu_497_p2;
        icmp_ln1027_3_reg_924 <= icmp_ln1027_3_fu_502_p2;
        mul_ln17_1_reg_907 <= grp_fu_368_p2;
        mul_ln17_3_reg_913 <= grp_fu_380_p2;
        sext_ln43_reg_887 <= sext_ln43_fu_441_p1;
        sext_ln73_1_reg_897[63 : 2] <= sext_ln73_1_fu_480_p1[63 : 2];
        sub_i_i228_reg_882 <= sub_i_i228_fu_424_p2;
        sub_i_i399_reg_877 <= sub_i_i399_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        gmem_addr_2_reg_982 <= sext_ln73_fu_633_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        gmem_addr_read_reg_988 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_fu_526_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        gmem_addr_reg_953 <= p_cast_cast_fu_569_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln17_2_reg_818 <= grp_fu_356_p2;
        mul_ln17_reg_811 <= grp_fu_344_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mul_ln38_reg_866 <= grp_fu_400_p2;
        mul_ln39_reg_872 <= grp_fu_406_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        mul_ln39_1_reg_959 <= grp_fu_537_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        mul_ln58_reg_977 <= grp_fu_615_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_2_fu_583_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        tmp_reg_972 <= tmp_fu_598_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_6_fu_647_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
        trunc_ln77_reg_1001 <= trunc_ln77_fu_658_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        x_V_2_reg_996 <= x_V_2_fu_652_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        y_V_1_reg_967 <= y_V_1_fu_588_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((gmem_AWREADY == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state24_blk = 1'b0;

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_done == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((gmem_WREADY == 1'b0)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

always @ (*) begin
    if ((gmem_BVALID == 1'b0)) begin
        ap_ST_fsm_state34_blk = 1'b1;
    end else begin
        ap_ST_fsm_state34_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln1027_fu_526_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1027_fu_526_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        coeff_cache_address0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_coeff_cache_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        coeff_cache_address0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_address0;
    end else begin
        coeff_cache_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        coeff_cache_ce0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_coeff_cache_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        coeff_cache_ce0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_ce0;
    end else begin
        coeff_cache_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        coeff_cache_we0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_coeff_cache_we0;
    end else begin
        coeff_cache_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        gmem_ARADDR = gmem_addr_reg_953;
    end else if (((1'b1 == ap_CS_fsm_state17) | ((icmp_ln1027_2_fu_583_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)))) begin
        gmem_ARADDR = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state15))) begin
        gmem_ARADDR = grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        gmem_ARLEN = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state17) | ((icmp_ln1027_2_fu_583_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)))) begin
        gmem_ARLEN = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state15))) begin
        gmem_ARLEN = grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state17) | ((icmp_ln1027_2_fu_583_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)))) begin
        gmem_ARVALID = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state15))) begin
        gmem_ARVALID = grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        gmem_RREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state17) | ((icmp_ln1027_2_fu_583_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)))) begin
        gmem_RREADY = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state15))) begin
        gmem_RREADY = grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_400_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_400_p_ce;
    end else begin
        grp_fu_400_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_400_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_400_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_400_p0 = convHeight_cast_fu_389_p1;
    end else begin
        grp_fu_400_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_400_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_400_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_400_p1 = convWidth_cast_fu_392_p1;
    end else begin
        grp_fu_400_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_406_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_406_p_ce;
    end else begin
        grp_fu_406_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_406_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_406_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_406_p0 = numChannels_cast_fu_386_p1;
    end else begin
        grp_fu_406_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_406_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_grp_fu_406_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_406_p1 = convHeight_cast_fu_389_p1;
    end else begin
        grp_fu_406_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state21) | ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        grp_fu_615_ce = 1'b1;
    end else begin
        grp_fu_615_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        row_buffer_address0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_row_buffer_address0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        row_buffer_address0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_address0;
    end else begin
        row_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        row_buffer_ce0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_row_buffer_ce0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        row_buffer_ce0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_ce0;
    end else begin
        row_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        row_buffer_we0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_row_buffer_we0;
    end else begin
        row_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln1027_fu_526_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln1027_2_fu_583_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            if (((icmp_ln1027_6_fu_647_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_2_fu_684_p3 = ((and_ln96_fu_679_p2[0:0] == 1'b1) ? 32'd0 : acc_fu_666_p2);

assign acc_fu_666_p2 = (gmem_addr_read_reg_988 + grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_acc_2_out);

assign add_ln1027_4_fu_521_p2 = ($signed(phi_mul_fu_144) + $signed(sext_ln43_reg_887));

assign add_ln1027_fu_516_p0 = phi_mul147_fu_140;

assign add_ln1027_fu_516_p2 = ($signed(add_ln1027_fu_516_p0) + $signed(convWidth_cast_reg_855));

assign add_ln58_1_fu_619_p2 = (mul_ln58_reg_977 + output_r_read_reg_775);

assign add_ln58_fu_474_p2 = ($signed(zext_ln58_1_fu_470_p1) + $signed(35'd34359738360));

assign add_ln73_fu_484_p2 = ($signed(inputWidth_read_reg_742) + $signed(32'd4294967294));

assign add_ln840_fu_531_p2 = (iFilter_V_fu_148 + 32'd1);

assign and_ln96_fu_679_p2 = (tmp_2_fu_671_p3 & apply_relu_read_reg_713);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state14 = ap_NS_fsm[32'd13];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp_i2051307_fu_435_p2 = (($signed(sub_i_i228_fu_424_p2) > $signed(33'd0)) ? 1'b1 : 1'b0);

assign cmp_i5691284_fu_430_p2 = ((convWidth_read_reg_726 != 32'd0) ? 1'b1 : 1'b0);

assign cmp_i5741286_fu_395_p2 = ((convHeight_read_reg_718 != 32'd0) ? 1'b1 : 1'b0);

assign convHeight_cast_fu_389_p1 = convHeight_read_reg_718;

assign convWidth_cast_fu_392_p1 = convWidth_read_reg_726;

assign empty_57_fu_489_p3 = ((cmp_i2051307_fu_435_p2[0:0] == 1'b1) ? add_ln73_fu_484_p2 : 32'd0);

assign empty_58_fu_554_p2 = (p_cast11_fu_550_p1 + biases_read_reg_765);

assign empty_fu_456_p3 = ((cmp_i5741286_reg_861[0:0] == 1'b1) ? select_ln43_fu_448_p3 : 32'd0);

assign grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_start = grp_Conv2D_HW_Pipeline_VITIS_LOOP_44_4_fu_280_ap_start_reg;

assign grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_start = grp_Conv2D_HW_Pipeline_VITIS_LOOP_66_8_fu_295_ap_start_reg;

assign grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_start = grp_Conv2D_HW_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_80_11_VITIS_LOOP_83_12_fu_311_ap_start_reg;

assign grp_fu_344_p0 = grp_fu_344_p00;

assign grp_fu_344_p00 = convHeight_read_reg_718;

assign grp_fu_344_p1 = grp_fu_344_p10;

assign grp_fu_344_p10 = convWidth_read_reg_726;

assign grp_fu_356_p0 = grp_fu_356_p00;

assign grp_fu_356_p00 = numChannels_read_reg_758;

assign grp_fu_356_p1 = grp_fu_356_p10;

assign grp_fu_356_p10 = inputWidth_read_reg_742;

assign grp_fu_368_p0 = grp_fu_368_p00;

assign grp_fu_368_p00 = numChannels_read_reg_758;

assign grp_fu_368_p1 = grp_fu_368_p10;

assign grp_fu_368_p10 = mul_ln17_reg_811;

assign grp_fu_380_p0 = grp_fu_380_p00;

assign grp_fu_380_p00 = convHeight_read_reg_718;

assign grp_fu_380_p1 = grp_fu_380_p10;

assign grp_fu_380_p10 = mul_ln17_2_reg_818;

assign grp_fu_615_p1 = sext_ln73_1_reg_897;

assign icmp_ln1027_1_fu_497_p2 = ((convWidth_read_reg_726 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1027_2_fu_583_p2 = (($signed(sub_i_i399_reg_877) > $signed(zext_ln1027_fu_579_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1027_3_fu_502_p2 = ((inputWidth_read_reg_742 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1027_6_fu_647_p2 = (($signed(sub_i_i228_reg_882) > $signed(zext_ln1027_1_fu_643_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_526_p2 = ((iFilter_V_fu_148 == numFilters_read_reg_753) ? 1'b1 : 1'b0);

assign inputHeight_cast_fu_412_p1 = inputHeight_read_reg_736;

assign inputWidth_cast_fu_421_p1 = inputWidth_read_reg_742;

assign numChannels_cast_fu_386_p1 = numChannels_read_reg_758;

assign p_cast11_fu_550_p1 = tmp_1_fu_542_p3;

assign p_cast_cast_fu_569_p1 = $signed(p_cast_fu_559_p4);

assign p_cast_fu_559_p4 = {{empty_58_fu_554_p2[63:2]}};

assign select_ln43_fu_448_p3 = ((cmp_i5691284_fu_430_p2[0:0] == 1'b1) ? trunc_ln43_fu_445_p1 : 32'd0);

assign sext_ln43_fu_441_p1 = sub_i_i399_fu_415_p2;

assign sext_ln73_1_fu_480_p1 = $signed(add_ln58_fu_474_p2);

assign sext_ln73_fu_633_p1 = $signed(trunc_ln1_fu_623_p4);

assign shl_ln_fu_463_p3 = {{inputWidth_read_reg_742}, {2'd0}};

assign sub_i_i228_fu_424_p2 = ($signed(inputWidth_cast_fu_421_p1) + $signed(33'd8589934590));

assign sub_i_i399_fu_415_p2 = ($signed(inputHeight_cast_fu_412_p1) + $signed(33'd8589934590));

assign tmp_1_fu_542_p3 = {{iFilter_V_fu_148}, {2'd0}};

assign tmp_2_fu_671_p3 = acc_fu_666_p2[32'd31];

assign tmp_fu_598_p2 = (phi_mul_fu_144 + zext_ln58_fu_594_p1);

assign trunc_ln1_fu_623_p4 = {{add_ln58_1_fu_619_p2[63:2]}};

assign trunc_ln43_fu_445_p1 = mul_ln38_reg_866[31:0];

assign trunc_ln77_fu_658_p1 = x_V_reg_269[16:0];

assign x_V_2_fu_652_p2 = (x_V_reg_269 + 32'd1);

assign y_V_1_fu_588_p2 = (y_V_reg_257 + 32'd1);

assign zext_ln1027_1_fu_643_p1 = x_V_reg_269;

assign zext_ln1027_fu_579_p1 = y_V_reg_257;

assign zext_ln58_1_fu_470_p1 = shl_ln_fu_463_p3;

assign zext_ln58_fu_594_p1 = y_V_reg_257;

always @ (posedge ap_clk) begin
    convWidth_cast_reg_855[61:32] <= 30'b000000000000000000000000000000;
    sext_ln73_1_reg_897[1:0] <= 2'b00;
end

endmodule //Conv2D_HW
